### ISSUE TITLE
DKG service errors

### ISSUE THREAD

**Issue by bgyori** [indralab/mira#57]
Two errors that show up in the MIRA DKG service logs:

First error likely has to do with a name missing for some nodes resulting in an error when returning an `Entity` object.
```
INFO:     128.104.100.153:36244 - "GET /api/entity/ncbitaxon%3A11598 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/api.py", line 72, in get_entity
    return request.app.state.client.get_entity(curie)
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/client.py", line 291, in get_entity
    return Entity(**r[0])
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Entity
name
  field required (type=value_error.missing)
```

The second error has to do with transaction/session management of the Neo4j connection used by the app. We would have to have a way to refresh the connection of there is a problem like this:
```
INFO:     20.110.182.97:1098 - "GET /api/search?q=infect&limit=25 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
...
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/api.py", line 250, in search
    return request.app.state.client.search(q, limit=limit)
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/client.py", line 270, in search
    entities = [Entity(**n) for n in self.query_nodes(cypher)]
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/client.py", line 154, in query_nodes
    return [self.neo4j_to_node(res[0]) for res in self.query_tx(query) or []]
  File "/usr/local/lib/python3.8/dist-packages/mira/dkg/client.py", line 129, in query_tx
    tx = self.session.begin_transaction()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/_sync/work/session.py", line 440, in begin_transaction
    raise TransactionError(
neo4j.exceptions.TransactionError: Explicit transaction already open
```

**Comment by cthoyt** [comment]
I mentioned earlier that I wanted to improve the DKG construction to enforce that all entities have names, there are only on the scale of 7-10 nodes that don't have names. A couple options:

1. Skip those nodes (they're not interesting ones, mostly popping up from broken imports in the He group ontologies)
2. Add a non-null, blank string as the name
3. Make the name optional

**Comment by bgyori** [comment]
Yes, I think looking into the content itself is worthwhile, one specific example is ncbitaxon:11598, which, at least per the NCBI Taxonomy website does seem to have a name, so it's likely getting lost somewhere in the pipeline. Beyond that, I think we could improve the app, and add error handling to either make it return an Entity from a node, even if it doesn't have a name, or at least return an error code in a controlled way.

**Comment by cthoyt** [comment]
Okay now that I think about it, we have many more nodes with no names since we're adding xrefs (e.g., the pubchem nodes) so better to go down a path of making it optional.
